export const hubCopy = {
  en: {
    eyebrow: 'Free Marketing Tools',
    titleLead: 'Turn market noise into',
    titleAccent: 'insights you can act on',
    description: 'Check creator authenticity, competitor ads, creative performance, market benchmarks and app momentum—your first tool is free, with no sign-up required',
    cta: 'Free your first tool',
    liveLabel: 'Live samples from CreatiVault',
    trustTitle: "Clear about what’s real, what’s modeled and when it changed",
    closingTitle: 'Your first tool is free',
    closingAccent: 'Start exploring in seconds',
  },
  zh: {
    eyebrow: '免费营销工具',
    titleLead: '把市场噪音，变成',
    titleAccent: '可执行洞察',
    description: '免费检测达人真实性、竞品广告、素材表现、行业基准与 App 增长动向，第一次查询无需注册',
    cta: '免费使用第一个工具',
    liveLabel: 'CreatiVault 实时样例',
    trustTitle: '清楚标注哪些是事实、哪些是估算，以及数据何时发生变化',
    closingTitle: '你的第一个工具免费',
    closingAccent: '几秒钟开始探索',
  },
}

export const liveSignals = {
  en: [
    ['meta', '37 new Meta ads detected', '12 min ago'],
    ['pulse', 'Creative entered Fatigue', '28 min ago'],
    ['user', 'Creator authenticity score updated', '41 min ago'],
  ],
  zh: [
    ['meta', '发现 37 条新 Meta 广告', '12 分钟前'],
    ['pulse', '广告素材进入疲劳阶段', '28 分钟前'],
    ['user', '达人真实性评分已更新', '41 分钟前'],
  ],
}

export const categoryCopy = {
  creators: {
    no: '01',
    en: { title: 'Verify creators', description: 'Authenticity, contacts and partnership history you can trust' },
    zh: { title: '验证达人', description: '可信的受众真实性、联系方式与品牌合作历史' },
  },
  ads: {
    no: '02',
    en: { title: 'Read competitor moves', description: 'See what ads they run, how they perform and what is changing' },
    zh: { title: '读取竞对动作', description: '看清竞品在投什么、表现如何，以及正在发生什么变化' },
  },
  market: {
    no: '03',
    en: { title: 'Calibrate the market', description: 'Benchmarks, trends and app momentum in one place' },
    zh: { title: '校准市场', description: '用行业基准、趋势与 App 动量校准决策' },
  },
}

const commonTrust = {
  en: {
    methodology: 'We combine public platform observations with confidence-scored modeled metrics. Every result includes its source, time window and known limits',
    limitations: 'Modeled metrics are directional estimates, not platform-reported billing or attribution data',
  },
  zh: {
    methodology: '我们结合公开平台观测与带置信度的模型指标，每项结果都标注来源、时间窗口与已知限制',
    limitations: '模型指标用于方向判断，并不等同于平台账单或官方归因数据',
  },
}

export const tools = [
  {
    id: 'fake-followers', slug: 'fake-follower-checker', category: 'creators', signal: '01', icon: 'user-check', visual: 'authenticity',
    platforms: ['TikTok', 'Instagram', 'YouTube'], updated: { en: 'Updated 18 min ago', zh: '18 分钟前更新' },
    name: { en: 'Free Influencer Fake Follower Checker', zh: '免费达人假粉检测器' },
    shortName: { en: 'Fake Follower Checker', zh: '达人假粉检测' },
    benefit: { en: 'See the real audience behind the follower count', zh: '看见粉丝数背后的真实受众' },
    description: { en: 'Analyze public growth and engagement signals across TikTok, Instagram and YouTube', zh: '分析 TikTok、Instagram 与 YouTube 的公开粉丝增长和互动信号' },
    fields: [
      { type: 'platform', label: { en: 'Platform', zh: '平台' }, options: ['TikTok', 'Instagram', 'YouTube'] },
      { type: 'text', key: 'query', label: { en: 'Profile URL or @handle', zh: '主页 URL 或 @用户名' }, placeholder: '@mrbeast' },
    ],
    cta: { en: 'Check followers', zh: '检测粉丝质量' }, sample: '@mrbeast',
    signalSentence: { en: '@mrbeast has a high-authenticity audience because follower growth and engagement remain consistent. Updated 18 minutes ago · High confidence', zh: '@mrbeast 的受众真实性较高，因为粉丝增长与互动表现保持一致。18 分钟前更新 · 高置信度' },
    metrics: [
      { label: { en: 'Authenticity', zh: '真实性评分' }, value: '87', suffix: '/100', tone: 'blue' },
      { label: { en: 'Suspected followers', zh: '疑似假粉' }, value: '8–12', suffix: '%', tone: 'amber' },
      { label: { en: 'Peer percentile', zh: '同量级分位' }, value: '72', suffix: 'nd', tone: 'green' },
    ],
    evidence: {
      observed: { en: ['Follower velocity stayed stable for 90 days', 'Engagement is consistent across recent posts'], zh: ['近 90 天粉丝增长速度稳定', '近期内容互动表现保持一致'] },
      interpreted: { en: ['One short growth anomaly was detected', 'Audience quality is above peer median'], zh: ['检测到一次短期增长异常', '受众质量高于同量级中位数'] },
      next: { en: ['Review audience distribution before outreach', 'Check recent brand partnerships'], zh: ['建联前查看受众质量分布', '继续查询近期品牌合作'] },
    },
    signup: { en: 'See why this audience was flagged', zh: '查看受众被标记的完整原因' },
    fullItems: { en: ['Audience quality distribution', 'Follower anomaly timeline', 'Engagement authenticity', 'Peer benchmark percentile'], zh: ['受众质量分布', '粉丝异常增长时间线', '互动真实性', '同量级达人分位'] },
    paid: { en: ['Audit creators in bulk', 'Export PDF / CSV', 'Monitor audience quality'], zh: ['批量检测达人', '导出 PDF / CSV', '持续监控受众质量'] },
    paidCta: { en: 'Audit creators in bulk', zh: '批量检测达人' },
    related: ['influencer-brand-collaboration-checker', 'influencer-email-finder', 'influencer-video-downloader'],
    faqs: {
      en: [['How is the fake follower range calculated?', 'We combine public growth velocity, engagement consistency, audience overlap and anomaly signals. The range reflects model uncertainty'], ['Does it work for smaller creators?', 'Yes. Peer comparisons adapt to account size, platform and category when enough public history is available'], ['Why is the result a range?', 'A range communicates uncertainty more honestly than an unsupported exact percentage'], ['How often is data refreshed?', 'Cached profiles refresh on a rolling schedule, while high-interest profiles may update more frequently'], ['Do I need creator authorization?', 'No authorization is required for public profile analysis']],
      zh: [['假粉比例如何计算？', '综合公开粉丝增长、互动一致性、受众重叠与异常信号计算，区间用于表达模型不确定性'], ['是否支持小体量达人？', '支持，基准会根据账号体量、平台与品类自适应'], ['为什么结果是区间？', '区间比缺乏依据的精确百分比更诚实地表达不确定性'], ['多久更新一次？', '缓存账号滚动更新，高关注账号可能更频繁'], ['是否需要达人授权？', '分析公开主页无需达人授权']],
    },
    trust: commonTrust,
  },
  {
    id: 'email', slug: 'influencer-email-finder', category: 'creators', signal: '02', icon: 'mail', visual: 'email',
    platforms: ['TikTok', 'Instagram', 'YouTube'], updated: { en: 'Verified 24 min ago', zh: '24 分钟前验证' },
    name: { en: 'Influencer Email Finder', zh: '海外达人邮箱查找器' }, shortName: { en: 'Influencer Email Finder', zh: '达人邮箱查找' },
    benefit: { en: 'Find verified business contact without searching every profile', zh: '不用翻遍主页，也能找到已验证的商务邮箱' },
    description: { en: 'Match public business contacts to the correct creator profile and show verification freshness', zh: '将公开商务联系方式与正确的达人主页匹配，并展示最近验证时间' },
    fields: [{ type: 'platform', label: { en: 'Platform', zh: '平台' }, options: ['TikTok', 'Instagram', 'YouTube'] }, { type: 'text', key: 'query', label: { en: 'Profile URL or @handle', zh: '主页 URL 或 @用户名' }, placeholder: '@emilycreative' }],
    cta: { en: 'Find email', zh: '查找达人邮箱' }, sample: '@emilycreative',
    signalSentence: { en: 'A verified business email was found for @emilycreative because the contact matches two public profile sources. Verified 24 minutes ago · High confidence', zh: '已为 @emilycreative 找到验证商务邮箱，因为该联系方式与两个公开主页来源匹配。24 分钟前验证 · 高置信度' },
    metrics: [{ label: { en: 'Email status', zh: '邮箱状态' }, value: 'Found', tone: 'green' }, { label: { en: 'Masked email', zh: '遮罩邮箱' }, value: 'em•••@studio.co', tone: 'blue' }, { label: { en: 'Match confidence', zh: '匹配置信度' }, value: '94', suffix: '%', tone: 'green' }],
    evidence: { observed: { en: ['Business email appears on two public sources', 'Profile identity and domain are consistent'], zh: ['商务邮箱出现在两个公开来源', '主页身份与邮箱域名保持一致'] }, interpreted: { en: ['The address is likely active and business-facing', 'No suppression request is on record'], zh: ['该邮箱很可能仍有效且用于商务合作', '目前不存在隐藏请求'] }, next: { en: ['Reveal the one-time free contact', 'Check brand partnership context first'], zh: ['使用一次免费邮箱揭示', '先查看达人品牌合作背景'] } },
    signup: { en: 'Reveal my free verified email', zh: '免费揭示这个已验证邮箱' },
    fullItems: { en: ['One verified email reveal included', 'Source type and verification record', 'Creator identity match', 'Contactability assessment'], zh: ['赠送一次完整邮箱揭示', '邮箱来源与验证记录', '达人身份匹配依据', '可联系性判断'] },
    paid: { en: ['Unlock more verified contacts', 'Bulk verify and export', 'Add to Shortlist', 'Start outreach workflow'], zh: ['解锁更多验证邮箱', '批量验证与导出', '加入 Shortlist', '进入建联流程'] }, paidCta: { en: 'Unlock more contacts', zh: '解锁更多联系方式' },
    related: ['fake-follower-checker', 'influencer-brand-collaboration-checker', 'influencer-video-downloader'],
    faqs: { en: [['Where do emails come from?', 'Only publicly available business-facing sources are considered'], ['How are emails verified?', 'We check identity alignment, source freshness and non-invasive deliverability signals'], ['Do you include private emails?', 'No. Personal or private-only contacts are excluded'], ['Does a failed search use my free reveal?', 'No. The reward is consumed only when a contact is revealed'], ['Can a creator remove their information?', 'Yes. Opt-out and suppression requests are respected across future searches']], zh: [['邮箱来自哪里？', '只使用公开且面向商务合作的来源'], ['如何验证有效性？', '综合身份匹配、来源新鲜度与非侵入式可投递信号'], ['是否包含私人邮箱？', '不包含私人或非公开联系方式'], ['未找到是否消耗奖励？', '不会，只有实际揭示邮箱才消耗奖励'], ['达人如何移除信息？', '支持隐藏申请，并在后续查询中持续执行']] }, trust: commonTrust,
  },
  {
    id: 'video', slug: 'influencer-video-downloader', category: 'creators', signal: '03', icon: 'video', visual: 'video',
    platforms: ['TikTok', 'Instagram Reels', 'YouTube Shorts'], updated: { en: 'Parsed just now', zh: '刚刚解析' },
    name: { en: 'Influencer Video Downloader', zh: '达人视频下载器' }, shortName: { en: 'Influencer Video Downloader', zh: '达人视频下载' },
    benefit: { en: 'Preview, understand and save public creator videos', zh: '解析、理解并保存公开达人视频' },
    description: { en: 'Parse public short-form videos before saving a permitted copy', zh: '先解析公开视频，再保存你有权使用的副本' },
    fields: [{ type: 'text', key: 'query', label: { en: 'Public video URL', zh: '公开视频 URL' }, placeholder: 'https://www.tiktok.com/@creator/video/…' }], cta: { en: 'Prepare download', zh: '解析视频' }, sample: 'tiktok.com/@creator/video/7358…',
    signalSentence: { en: 'This public creator video is available in standard and HD formats. Parsed just now · High confidence', zh: '该公开视频可解析为标准与高清格式。刚刚解析 · 高置信度' },
    metrics: [{ label: { en: 'Duration', zh: '视频时长' }, value: '00:27', tone: 'blue' }, { label: { en: 'Aspect ratio', zh: '视频比例' }, value: '9:16', tone: 'blue' }, { label: { en: 'Formats', zh: '可用格式' }, value: 'MP4 · WEBM', tone: 'green' }],
    evidence: { observed: { en: ['Public video URL resolved successfully', 'Caption and creator metadata are available'], zh: ['公开视频 URL 解析成功', '可读取 Caption 与达人元数据'] }, interpreted: { en: ['Standard and HD source variants are available', 'Speech transcript can be generated'], zh: ['可获取标准与高清版本', '可以生成语音字幕'] }, next: { en: ['Use the one-time free standard download', 'Review usage rights before saving'], zh: ['使用一次免费标准下载', '保存前确认内容使用权'] } },
    signup: { en: 'Use my free download', zh: '使用我的免费标准下载' }, fullItems: { en: ['One standard-quality download included', 'Caption and publish date', 'Transcript or script', 'Basic performance data'], zh: ['赠送一次标准质量下载', 'Caption 与发布时间', '字幕或脚本', '基础表现数据'] },
    paid: { en: ['Download in HD', 'Bulk download', 'Save to creative library', 'Batch transcript extraction'], zh: ['高清下载', '批量下载', '保存到素材库', '批量提取字幕与脚本'] }, paidCta: { en: 'Download in HD or bulk', zh: '高清或批量下载' },
    related: ['fake-follower-checker', 'influencer-brand-collaboration-checker', 'ad-creative-performance-analyzer'],
    faqs: { en: [['Which platforms and formats are supported?', 'Public TikTok, Instagram Reels and YouTube Shorts URLs are supported when a permitted source is available'], ['Are downloads watermarked?', 'Availability depends on the public source. The preview clearly identifies the available variant'], ['What happens if parsing fails?', 'The URL stays in place and you can retry or choose a matched public result'], ['Can I use a download commercially?', 'Only if you hold the required rights or permission from the content owner'], ['What about deleted or private videos?', 'Private, removed, DRM-protected or access-controlled videos are not processed']], zh: [['支持哪些平台与格式？', '支持可公开访问且存在允许来源的 TikTok、Instagram Reels 与 YouTube Shorts'], ['是否带水印？', '取决于公开来源，预览会明确标注可用版本'], ['下载失败如何处理？', '系统会保留 URL，并允许重试或确认候选结果'], ['是否允许商业使用？', '仅限你已经拥有所需权利或获得内容所有者授权的情况'], ['删除或私密视频如何处理？', '不处理私密、已删除、DRM 或受访问控制的视频']] }, trust: { en: { methodology: 'We resolve public media metadata and permitted source variants without bypassing access controls', limitations: 'You are responsible for confirming copyright, usage rights and platform terms before downloading' }, zh: { methodology: '我们解析公开媒体元数据与允许访问的来源版本，不绕过访问控制', limitations: '下载前请自行确认版权、使用授权与平台条款' } },
  },
  {
    id: 'brands', slug: 'influencer-brand-collaboration-checker', category: 'creators', signal: '04', icon: 'handshake', visual: 'brands',
    platforms: ['TikTok', 'Instagram', 'YouTube'], updated: { en: 'Updated 36 min ago', zh: '36 分钟前更新' },
    name: { en: 'Influencer Brand Collaboration Checker', zh: '达人合作品牌查询器' }, shortName: { en: 'Brand Collaboration Checker', zh: '达人合作品牌查询' },
    benefit: { en: 'See which brands already trust this creator', zh: '看清哪些品牌已经与这个达人合作' }, description: { en: 'Map public sponsorship and brand-partnership signals across creator content', zh: '从达人公开内容中梳理赞助与品牌合作信号' },
    fields: [{ type: 'platform', label: { en: 'Platform', zh: '平台' }, options: ['Instagram', 'TikTok', 'YouTube'] }, { type: 'text', key: 'query', label: { en: 'Profile URL or @handle', zh: '主页 URL 或 @用户名' }, placeholder: '@creator' }], cta: { en: 'Check collaborations', zh: '查询合作品牌' }, sample: '@creator',
    signalSentence: { en: '@creator worked with 8 brands in the last 90 days, led by beauty and wellness partnerships. Updated 36 minutes ago · Medium-high confidence', zh: '@creator 近 90 天与 8 个品牌合作，主要集中在美妆与健康品类。36 分钟前更新 · 中高置信度' },
    metrics: [{ label: { en: 'Brands in 90 days', zh: '90 天合作品牌' }, value: '8', tone: 'blue' }, { label: { en: 'Repeat partners', zh: '重复合作品牌' }, value: '3', tone: 'green' }, { label: { en: 'Top category', zh: '主要品类' }, value: 'Beauty', tone: 'amber' }],
    evidence: { observed: { en: ['12 partnership posts were identified', 'Three brands appeared more than once'], zh: ['识别到 12 条品牌合作内容', '3 个品牌出现重复合作'] }, interpreted: { en: ['Beauty is the strongest category fit', 'Repeat partnerships suggest reliable delivery'], zh: ['美妆是最强合作品类', '重复合作意味着交付稳定性较高'] }, next: { en: ['Review full collaboration timeline', 'Check audience authenticity before outreach'], zh: ['查看完整合作时间线', '建联前检测受众真实性'] } },
    signup: { en: 'See the full collaboration history', zh: '查看完整品牌合作历史' }, fullItems: { en: ['Full brand timeline', 'Repeat partnerships', 'Category concentration', 'Linked content performance'], zh: ['完整品牌合作时间线', '重复合作记录', '品类集中度', '关联内容表现'] }, paid: { en: ['Export partnership records', 'Find similar creators', 'Reveal contact', 'Monitor new partnerships'], zh: ['导出合作记录', '查找相似达人', '解锁联系方式', '监控新增品牌合作'] }, paidCta: { en: 'Monitor new partnerships', zh: '监控新增品牌合作' },
    related: ['fake-follower-checker', 'influencer-email-finder', 'competitor-ad-tracker'],
    faqs: { en: [['How are commercial collaborations identified?', 'We use sponsorship disclosures, brand mentions, links, captions and recurring content patterns'], ['Are untagged ads included?', 'Some may be included as Estimated when multiple commercial signals align'], ['How much history is covered?', 'Coverage varies by platform and public availability, with recent content prioritized'], ['How are duplicate brand names merged?', 'Brand aliases and domains are normalized into one entity where confidence is sufficient'], ['Why do some partnerships say Estimated?', 'The label appears when the relationship is inferred rather than explicitly disclosed']], zh: [['如何识别商业合作？', '综合赞助披露、品牌提及、链接、Caption 与重复内容模式'], ['是否包含未标记广告内容？', '当多个商业信号一致时，部分内容会以 Estimated 标注'], ['历史覆盖多长时间？', '覆盖随平台和公开可用性变化，优先近期内容'], ['品牌名称如何合并？', '在置信度足够时，将别名与域名归并为同一品牌实体'], ['为什么部分合作显示 Estimated？', '当合作关系来自推断而非明确披露时会显示该标签']] }, trust: commonTrust,
  },
  {
    id: 'competitor', slug: 'competitor-ad-tracker', category: 'ads', signal: '05', icon: 'radar', visual: 'activity',
    platforms: ['Meta', 'TikTok'], updated: { en: 'Updated 12 min ago', zh: '12 分钟前更新' },
    name: { en: 'Competitor Ad Tracker', zh: '竞品广告素材追踪器' }, shortName: { en: 'Competitor Ad Tracker', zh: '竞品广告追踪' },
    benefit: { en: 'Know when competitors launch, scale or retire ads', zh: '第一时间知道竞品何时上新、起量或下线素材' }, description: { en: 'See active ads, launch cadence and fresh creative signals across Meta and TikTok', zh: '查看竞品在 Meta 与 TikTok 的活跃广告、上新节奏与新素材信号' },
    fields: [{ type: 'platform', label: { en: 'Platform', zh: '平台' }, options: ['Meta', 'TikTok'] }, { type: 'text', key: 'query', label: { en: 'Brand, domain or advertiser', zh: '品牌、域名或广告主' }, placeholder: 'notion.so' }, { type: 'select', key: 'country', label: { en: 'Country', zh: '国家' }, options: ['United States', 'United Kingdom', 'Germany', 'France'] }], cta: { en: 'Check competitor ads', zh: '查看竞品广告' }, sample: 'notion.so',
    signalSentence: { en: 'Notion is increasing Meta ad activity because 37 new creatives appeared in the last 7 days. Updated 12 minutes ago · High confidence', zh: 'Notion 正在增加 Meta 广告活动，因为过去 7 天出现了 37 条新素材。12 分钟前更新 · 高置信度' },
    metrics: [{ label: { en: 'Active ads', zh: '活跃广告' }, value: '128', tone: 'blue' }, { label: { en: 'New in 7 days', zh: '7 天新增素材' }, value: '37', tone: 'amber' }, { label: { en: 'Latest launch', zh: '最近上线' }, value: '2h ago', zhValue: '2 小时前', tone: 'green' }],
    evidence: { observed: { en: ['37 new creatives in 7 days versus 7-day baseline of 40%', 'Placements expanded across Feed, Story and Reels'], zh: ['7 天新增 37 条素材，高于常态 40%', '版位扩展至 Feed、Story 与 Reels'] }, interpreted: { en: ['Notion is testing new angles at scale', 'Broader placements suggest a scaling phase'], zh: ['Notion 正在规模化测试新角度', '更广版位意味着进入起量阶段'] }, next: { en: ['Monitor these creatives for the next 7–14 days', 'Analyze top-performing angles'], zh: ['未来 7–14 天持续观察这批素材', '分析其中表现最好的创意角度'] } },
    signup: { en: 'See the full 30-day activity', zh: '查看完整 30 天投放动作' }, fullItems: { en: ['Full creative stream', '7 / 14 / 30-day cadence', 'Landing pages', 'Platform, country and format breakdown'], zh: ['完整素材流', '7 / 14 / 30 天投放趋势', '落地页', '平台、国家与格式拆分'] }, paid: { en: ['Track this advertiser', 'Launch and scaling alerts', 'Export CSV / PDF', 'Download original creative'], zh: ['持续追踪广告主', '上新与起量提醒', '导出 CSV / PDF', '下载原始素材'] }, paidCta: { en: 'Track this advertiser', zh: '持续追踪这个广告主' },
    related: ['ad-creative-performance-analyzer', 'ad-creative-lifecycle-checker', 'advertising-benchmark-report'],
    faqs: { en: [['Which ad platforms are supported?', 'The prototype covers Meta and TikTok public advertising data'], ['How is an Active Ad defined?', 'An ad is active when it remains publicly observable within the selected recency window'], ['How often is data refreshed?', 'High-interest advertisers refresh frequently; every result shows its last observation time'], ['Can I track multiple countries?', 'Paid tracking supports saved country and platform combinations'], ['How is this different from Meta Ads Library?', 'CreatiVault adds historical cadence, modeled performance context, cross-platform normalization and alerts']], zh: [['支持哪些广告平台？', '当前原型覆盖 Meta 与 TikTok 公开广告数据'], ['Active Ads 如何定义？', '在所选新鲜度窗口中仍可公开观察到的广告被视为活跃'], ['数据多久更新？', '高关注广告主更新更频繁，每项结果都显示最近观察时间'], ['是否能追踪多个国家？', '付费追踪支持保存多个国家与平台组合'], ['与 Meta Ads Library 有何区别？', 'CreatiVault 增加历史节奏、模型表现背景、跨平台标准化与提醒']] }, trust: commonTrust,
  },
  {
    id: 'performance', slug: 'ad-creative-performance-analyzer', category: 'ads', signal: '06', icon: 'chart', visual: 'performance',
    platforms: ['Meta', 'TikTok'], updated: { en: 'Calculated 9 min ago', zh: '9 分钟前计算' },
    name: { en: 'Ad Creative Performance Analyzer', zh: '广告素材表现分析器' }, shortName: { en: 'Creative Performance Analyzer', zh: '素材表现分析' },
    benefit: { en: 'Find out whether a creative is truly outperforming', zh: '判断一条素材是否真的正在跑赢同类' }, description: { en: 'Compare creative longevity, reach and modeled performance against relevant peers', zh: '将素材运行时长、触达与模型表现和相关同类进行比较' },
    fields: [{ type: 'text', key: 'query', label: { en: 'Ad or creative URL', zh: '广告或素材 URL' }, placeholder: 'Paste a Meta or TikTok ad URL' }], cta: { en: 'Analyze creative', zh: '分析素材表现' }, sample: 'facebook.com/ads/library/?id=…',
    signalSentence: { en: 'This creative is outperforming its peer set because longevity and reach signals place it in the top 18%. Calculated 9 minutes ago · Medium-high confidence', zh: '该素材正在跑赢同类，因为运行时长与触达信号使其进入前 18%。9 分钟前计算 · 中高置信度' },
    metrics: [{ label: { en: 'Performance signal', zh: '表现信号' }, value: '82', suffix: '/100', tone: 'blue' }, { label: { en: 'Estimated spend', zh: '预估消耗' }, value: '$18–26K', tone: 'amber' }, { label: { en: 'Peer percentile', zh: '同类分位' }, value: 'Top 18%', tone: 'green' }],
    evidence: { observed: { en: ['Creative remained active for 24 days', 'Placement coverage expanded after day 8'], zh: ['素材已持续活跃 24 天', '第 8 天后版位覆盖扩大'] }, interpreted: { en: ['Longevity and reach indicate durable performance', 'Hook retention is stronger than category peers'], zh: ['运行时长与触达表明表现可持续', '开场 Hook 留存高于品类同类'] }, next: { en: ['Review the winning hook and CTA', 'Check whether fatigue is beginning'], zh: ['拆解获胜 Hook 与 CTA', '检测是否已经开始疲劳'] } },
    signup: { en: 'See the performance breakdown', zh: '查看完整表现拆解' }, fullItems: { en: ['Performance trend', 'Peer benchmark', 'Hook and CTA analysis', 'Second-by-second effect curve'], zh: ['完整表现趋势', '同行 Benchmark', 'Hook 与 CTA 分析', '秒级效果曲线'] }, paid: { en: ['Compare multiple creatives', 'Export report', 'Download original', 'Monitor performance'], zh: ['多素材比较', '导出报告', '下载原始素材', '持续表现监控'] }, paidCta: { en: 'Compare and export', zh: '对比并导出' },
    related: ['competitor-ad-tracker', 'ad-creative-lifecycle-checker', 'advertising-benchmark-report'],
    faqs: { en: [['How is Performance Signal calculated?', 'It combines longevity, reach, engagement, placement and category-relative signals'], ['Why are spend and reach ranges?', 'Public ad data does not always disclose exact delivery, so estimates are shown as ranges'], ['Can different platforms be compared directly?', 'Only normalized directional scores are compared; raw platform metrics remain separate'], ['Does a long-running ad always perform well?', 'No. Longevity is one signal and is interpreted alongside reach, changes and peer context'], ['How often is the score recalculated?', 'Scores refresh when material new observations arrive']], zh: [['Performance Score 如何计算？', '综合运行时长、触达、互动、版位与同品类相对信号'], ['为什么使用估算区间？', '公开广告数据并不总披露精确投放量，因此以区间表达'], ['不同平台能否直接比较？', '只比较标准化方向评分，平台原始指标仍保持分离'], ['运行时间长是否一定表现好？', '不一定，时长只是其中一个信号，还需结合触达、变化与同类背景'], ['多久重新计算一次？', '出现重要新观测时重新计算']] }, trust: commonTrust,
  },
  {
    id: 'lifecycle', slug: 'ad-creative-lifecycle-checker', category: 'ads', signal: '07', icon: 'cycle', visual: 'lifecycle',
    platforms: ['Meta', 'TikTok'], updated: { en: 'Updated 14 min ago', zh: '14 分钟前更新' },
    name: { en: 'Ad Creative Lifecycle & Fatigue Checker', zh: '广告素材生命周期与疲劳检测器' }, shortName: { en: 'Creative Lifecycle Checker', zh: '素材生命周期检测' },
    benefit: { en: 'Know when a winning creative starts losing momentum', zh: '在爆款素材失速之前，看见疲劳信号' }, description: { en: 'Identify Testing, Scaling, Mature and Fatigue stages from observable momentum', zh: '依据可观察动量判断 Testing、Scaling、Mature 与 Fatigue 阶段' },
    fields: [{ type: 'text', key: 'query', label: { en: 'Ad or creative URL', zh: '广告或素材 URL' }, placeholder: 'Paste a Meta or TikTok ad URL' }], cta: { en: 'Check lifecycle', zh: '检测素材生命周期' }, sample: 'tiktok.com/business/creativecenter/…',
    signalSentence: { en: 'This creative has entered early Fatigue because active placement growth slowed for three consecutive days. Updated 14 minutes ago · Medium-high confidence', zh: '该素材已进入早期疲劳，因为活跃版位增长连续 3 天放缓。14 分钟前更新 · 中高置信度' },
    metrics: [{ label: { en: 'Current stage', zh: '当前阶段' }, value: 'Fatigue', tone: 'risk' }, { label: { en: 'Running days', zh: '运行天数' }, value: '31', tone: 'blue' }, { label: { en: 'Momentum score', zh: '动量评分' }, value: '43', suffix: '/100', tone: 'amber' }],
    evidence: { observed: { en: ['Placement growth slowed for three days', 'No new creative variants appeared'], zh: ['版位增长连续 3 天放缓', '没有出现新的素材变体'] }, interpreted: { en: ['The creative is moving from Mature to Fatigue', 'Audience saturation risk is rising'], zh: ['素材正从 Mature 进入 Fatigue', '受众饱和风险正在上升'] }, next: { en: ['Prepare a refreshed hook or visual variant', 'Create a fatigue alert'], zh: ['准备更新 Hook 或视觉变体', '创建疲劳提醒'] } },
    signup: { en: 'See the evidence behind this lifecycle stage', zh: '查看生命周期判断依据' }, fullItems: { en: ['Full lifecycle curve', 'Stage transition dates', 'Creative variants', 'Peer lifespan benchmark'], zh: ['完整生命周期曲线', '阶段切换时间', '素材变体', '同类寿命 Benchmark'] }, paid: { en: ['Create fatigue alert', 'Batch check creatives', 'Export history', 'Track creative portfolio'], zh: ['创建疲劳提醒', '批量检测素材', '导出历史', '追踪素材组合'] }, paidCta: { en: 'Alert me before this creative fades', zh: '在素材衰退前提醒我' },
    related: ['ad-creative-performance-analyzer', 'competitor-ad-tracker', 'advertising-benchmark-report'],
    faqs: { en: [['How is ad fatigue defined?', 'Fatigue is a sustained loss of momentum relative to the creative’s own baseline and peer context'], ['How are lifecycle stages assigned?', 'Stages use observed duration, placement growth, reach momentum, variants and category benchmarks'], ['What if a creative starts scaling again?', 'The lifecycle can move back to Scaling when material positive momentum returns'], ['Can I use this for my own ads?', 'Yes. First-party data can improve confidence when connected in production'], ['How much history is needed?', 'Confidence improves with time, while early-stage labels remain provisional']], zh: [['如何定义广告疲劳？', '疲劳是素材相对于自身基线与同类背景持续失去动量'], ['生命周期阶段如何判断？', '综合持续时间、版位增长、触达动量、素材变体与品类基准'], ['素材重新起量如何处理？', '当显著正向动量回归时，阶段可以重新进入 Scaling'], ['建议是否适用于自有广告？', '适用，生产环境接入第一方数据后置信度会更高'], ['需要多久的数据才能判断？', '历史越长置信度越高，早期阶段标签会保持暂定']] }, trust: commonTrust,
  },
  {
    id: 'benchmark', slug: 'advertising-benchmark-report', category: 'market', signal: '08', icon: 'benchmark', visual: 'benchmark',
    platforms: ['Meta', 'TikTok'], updated: { en: 'Updated today', zh: '今天更新' },
    name: { en: 'Digital Advertising Benchmark Report', zh: '数字广告投放基准报告' }, shortName: { en: 'Advertising Benchmark Report', zh: '广告投放基准' },
    benefit: { en: 'Calibrate your KPIs against the market you actually compete in', zh: '用真实市场基准校准你的投放 KPI' }, description: { en: 'Compare CPM, CTR, CVR and ROAS by platform, industry, country and recency', zh: '按平台、行业、国家与周期比较 CPM、CTR、CVR 和 ROAS' },
    fields: [{ type: 'platform', label: { en: 'Platform', zh: '平台' }, options: ['Meta', 'TikTok'] }, { type: 'select', key: 'industry', label: { en: 'Industry', zh: '行业' }, options: ['Beauty', 'Gaming', 'Fashion', 'Consumer Tech'] }, { type: 'select', key: 'country', label: { en: 'Country', zh: '国家' }, options: ['United States', 'United Kingdom', 'Germany', 'France'] }, { type: 'select', key: 'window', label: { en: 'Window', zh: '周期' }, options: ['7 days', '14 days', '30 days'] }], cta: { en: 'Get benchmarks', zh: '查询行业基准' }, sample: 'Meta · Beauty · United States',
    signalSentence: { en: 'US Beauty CTR is improving while CPM remains above the 30-day median. Updated today · High confidence', zh: '美国美妆行业 CTR 正在改善，但 CPM 仍高于 30 天中位数。今天更新 · 高置信度' },
    metrics: [{ label: { en: 'CPM', zh: 'CPM' }, value: '$8.42', tone: 'amber' }, { label: { en: 'CTR', zh: 'CTR' }, value: '2.91', suffix: '%', tone: 'green' }, { label: { en: 'CVR', zh: 'CVR' }, value: '3.24', suffix: '%', tone: 'blue' }, { label: { en: 'ROAS', zh: 'ROAS' }, value: '2.8×', tone: 'green' }],
    evidence: { observed: { en: ['CTR improved 0.18 points week over week', 'CPM remains 12% above the 30-day median'], zh: ['CTR 周环比提升 0.18 个百分点', 'CPM 仍高于 30 天中位数 12%'] }, interpreted: { en: ['Creative relevance is improving', 'Reach cost still needs audience or placement review'], zh: ['素材相关性正在改善', '触达成本仍需排查受众或版位'] }, next: { en: ['Compare your own KPI values', 'Inspect winning category creatives'], zh: ['输入并比较自有 KPI', '查看品类获胜素材'] } },
    signup: { en: 'Compare my KPIs with the market', zh: '把我的 KPI 与市场进行比较' }, fullItems: { en: ['Complete trend history', 'Market percentile', 'Country detail', 'Gap and optimization advice'], zh: ['完整趋势', '行业分位', '国家明细', '指标差距与优化建议'] }, paid: { en: ['Export PDF / CSV', 'Save filter combinations', 'Schedule benchmark report', 'Custom slices and API'], zh: ['导出 PDF / CSV', '保存筛选组合', '周期基准报告', '自定义切片与 API'] }, paidCta: { en: 'Schedule this benchmark report', zh: '订阅这份基准报告' },
    related: ['competitor-ad-tracker', 'ad-creative-performance-analyzer', 'app-game-downloads-revenue-tracker'],
    faqs: { en: [['Where does benchmark data come from?', 'Benchmarks combine normalized aggregated campaign observations and modeled market signals'], ['How are industries and countries filtered?', 'Taxonomy and geography are normalized before minimum sample thresholds are applied'], ['What happens with a small sample?', 'The page widens the time window or shows a lower-confidence label instead of false precision'], ['Can different attribution models be compared?', 'Directional context can be compared, while raw values must retain their attribution caveats'], ['How often should I check benchmarks?', 'Weekly is useful for active spend, with monthly reviews for broader planning']], zh: [['Benchmark 数据来自哪里？', '由标准化聚合投放观测与模型市场信号构成'], ['行业与国家样本如何筛选？', '统一分类与地理口径后应用最低样本阈值'], ['样本不足如何处理？', '扩大时间窗口或降低置信度，而不是展示伪精确结果'], ['不同归因口径是否可比较？', '可比较方向背景，但原始值必须保留归因说明'], ['建议多久查看一次？', '活跃投放建议每周查看，整体规划可按月复盘']] }, trust: commonTrust,
  },
  {
    id: 'app', slug: 'app-game-downloads-revenue-tracker', category: 'market', signal: '09', icon: 'smartphone', visual: 'app',
    platforms: ['App Store', 'Google Play'], updated: { en: 'Updated 22 min ago', zh: '22 分钟前更新' },
    name: { en: 'App & Mobile Game Downloads and Revenue Tracker', zh: 'App 与手游下载量及收入趋势查询器' }, shortName: { en: 'App & Game Momentum Tracker', zh: 'App 与手游趋势' },
    benefit: { en: 'See which apps and games are gaining real market momentum', zh: '发现真正开始获得市场动量的 App 与手游' }, description: { en: 'Track estimated downloads, revenue and rank changes by store, country and time', zh: '按商店、国家与周期追踪预估下载、收入与排名变化' },
    fields: [{ type: 'select', key: 'store', label: { en: 'Store', zh: '商店' }, options: ['App Store', 'Google Play'] }, { type: 'text', key: 'query', label: { en: 'App name or store URL', zh: 'App 名称或商店 URL' }, placeholder: 'Monopoly GO!' }, { type: 'select', key: 'country', label: { en: 'Country', zh: '国家' }, options: ['United States', 'United Kingdom', 'Japan', 'Germany'] }, { type: 'select', key: 'window', label: { en: 'Window', zh: '周期' }, options: ['30 days', '90 days', '12 months'] }], cta: { en: 'Check app momentum', zh: '查询 App 增长动向' }, sample: 'Monopoly GO!',
    signalSentence: { en: 'Monopoly GO! is gaining download momentum while revenue growth remains steady. Updated 22 minutes ago · Medium-high confidence', zh: 'Monopoly GO! 下载动量正在提升，同时收入增长保持稳定。22 分钟前更新 · 中高置信度' },
    metrics: [{ label: { en: 'Est. downloads', zh: '预估下载量' }, value: '3.8M', tone: 'blue' }, { label: { en: 'Est. revenue', zh: '预估收入' }, value: '$42M', tone: 'green' }, { label: { en: '7-day growth', zh: '7 天增长' }, value: '+18', suffix: '%', tone: 'green' }, { label: { en: 'Category rank', zh: '品类排名' }, value: '#4', tone: 'amber' }],
    evidence: { observed: { en: ['Store rank rose six positions in seven days', 'Review velocity increased in the US'], zh: ['商店排名 7 天提升 6 位', '美国评论增长速度上升'] }, interpreted: { en: ['Acquisition momentum is strengthening', 'Revenue growth remains stable rather than accelerating'], zh: ['获客动量正在增强', '收入增长保持稳定但尚未加速'] }, next: { en: ['Inspect publisher ad activity', 'Add this app to a watchlist'], zh: ['查看发行商广告活动', '将该 App 加入 Watchlist'] } },
    signup: { en: 'See the full 12-month trend', zh: '查看完整 12 个月趋势' }, fullItems: { en: ['Download trend', 'Revenue trend', 'Country distribution', 'Store split and similar apps'], zh: ['下载趋势', '收入趋势', '国家分布', '商店拆分与相似 App'] }, paid: { en: ['Track this app', 'Build a watchlist', 'Compare multiple apps', 'Export and create alerts'], zh: ['持续追踪 App', '建立 Watchlist', '多 App 比较', '导出并创建异动提醒'] }, paidCta: { en: 'Track this app', zh: '持续追踪这个 App' },
    related: ['competitor-ad-tracker', 'ad-creative-performance-analyzer', 'advertising-benchmark-report'],
    faqs: { en: [['How are downloads and revenue estimated?', 'We combine public ranking, review velocity, market panels and calibrated category models'], ['Does revenue include advertising?', 'The prototype primarily models store revenue; advertising revenue is labeled separately when available'], ['Which stores and countries are supported?', 'App Store and Google Play coverage varies by country and public signal availability'], ['How often does data update?', 'Rank and momentum signals update frequently, while longer-horizon estimates refresh on a rolling schedule'], ['How are app renames or removals handled?', 'Store identifiers remain the primary key so history can survive name changes']], zh: [['下载量与收入如何估算？', '综合公开排名、评论增速、市场面板与经过校准的品类模型'], ['是否包含广告收入？', '原型主要估算商店收入，可用时会单独标注广告收入'], ['支持哪些商店与国家？', '覆盖 App Store 与 Google Play，具体国家取决于公开信号可用性'], ['多久更新一次？', '排名与动量高频更新，长期估算滚动刷新'], ['App 更名或下架如何处理？', '以商店标识作为主键，使历史数据能跨越名称变化']] }, trust: commonTrust,
  },
]

export const getTool = (slug) => tools.find((tool) => tool.slug === slug)

export const uiCopy = {
  en: {
    nav: ['Free Tools', 'Creators', 'Ads', 'Market', 'Pricing'], start: 'Start Free', run: 'Run tool', firstFree: 'First tool free', noSignup: 'No sign-up required',
    observed: 'Observed', interpreted: 'Interpreted', next: 'Next move', complete: 'Complete analysis', paid: 'Continue with CreatiVault', related: 'Explore related tools', faq: 'Frequently asked questions', methodology: 'Methodology', limitations: 'Known limitations',
    lastChecked: 'Last checked', confidence: 'Confidence', estimated: 'Estimated', high: 'High', signupAction: 'Start Free to unlock', paidAction: 'View paid actions', retry: 'Try again', useExample: 'Use example',
    states: { idle: 'Idle', validating: 'Validating input', running: 'Reading live data', preview: 'Preview', signup: 'Signup gate', full: 'Full result', paid: 'Paid gate', partial: 'Partial match', noresult: 'No result', ratelimit: 'Rate limit', error: 'Error' },
  },
  zh: {
    nav: ['免费工具', '达人', '广告', '市场', '定价'], start: '免费开始', run: '运行工具', firstFree: '第一个工具免费', noSignup: '无需注册',
    observed: 'Observed · 已观察', interpreted: 'Interpreted · 已解读', next: 'Next move · 下一步', complete: '完整分析', paid: '继续使用 CreatiVault', related: '探索相关工具', faq: '常见问题', methodology: '方法论', limitations: '已知限制',
    lastChecked: '最近检查', confidence: '置信度', estimated: 'Estimated · 估算', high: '高', signupAction: '免费注册并解锁', paidAction: '查看付费动作', retry: '重试', useExample: '使用示例',
    states: { idle: '初始', validating: '正在验证输入', running: '正在读取实时数据', preview: '匿名结果', signup: '注册门槛', full: '完整结果', paid: '付费门槛', partial: '候选匹配', noresult: '无结果', ratelimit: '已达限制', error: '错误' },
  },
}
